<?php
/**
 * Zoho-Parasut-Sync — Setup Wizard
 * Browser-based installation: DB connection → Tables → Admin password
 * No file editing required — everything configured through this wizard.
 */

// Basic session for wizard state
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// If already installed, redirect to login
if (file_exists(__DIR__ . '/.env')) {
    try {
        $lines = file(__DIR__ . '/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        $env = [];
        foreach ($lines as $line) {
            $line = trim($line);
            if ($line === '' || $line[0] === '#') continue;
            if (strpos($line, '=') === false) continue;
            [$key, $value] = explode('=', $line, 2);
            $env[trim($key)] = trim($value);
        }
        if (!empty($env['DB_NAME']) && !empty($env['DB_USER'])) {
            $testPdo = new PDO(
                "mysql:host=" . ($env['DB_HOST'] ?? 'localhost') . ";dbname=" . $env['DB_NAME'] . ";charset=utf8mb4",
                $env['DB_USER'], $env['DB_PASS'] ?? ''
            );
            $tableCheck = $testPdo->query("SHOW TABLES LIKE 'settings'")->rowCount();
            if ($tableCheck > 0) {
                header('Location: login.php');
                exit;
            }
        }
    } catch (Exception $e) {
        // .env exists but DB connection fails — continue with wizard
    }
}

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// ============================================================
// STEP HANDLERS (POST)
// ============================================================

if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // STEP 1: Test DB connection and save .env
    if ($step === 1) {
        $dbHost = trim($_POST['db_host'] ?? 'localhost');
        $dbName = trim($_POST['db_name'] ?? '');
        $dbUser = trim($_POST['db_user'] ?? '');
        $dbPass = $_POST['db_pass'] ?? '';

        if (empty($dbName) || empty($dbUser)) {
            $error = 'Veritabanı adı ve kullanıcı adı zorunludur.';
        } else {
            try {
                $testPdo = new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4", $dbUser, $dbPass);
                $testPdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                // Save .env
                $envContent = "# Zoho-Parasut-Sync Environment Configuration\n";
                $envContent .= "# Auto-generated by setup wizard\n\n";
                $envContent .= "# Database\n";
                $envContent .= "DB_HOST=$dbHost\n";
                $envContent .= "DB_NAME=$dbName\n";
                $envContent .= "DB_USER=$dbUser\n";
                $envContent .= "DB_PASS=$dbPass\n";

                if (file_put_contents(__DIR__ . '/.env', $envContent) === false) {
                    $error = '.env dosyası oluşturulamadı. Dizin yazma izinlerini kontrol edin.';
                } else {
                    $_SESSION['install_db_ok'] = true;
                    header('Location: install.php?step=2');
                    exit;
                }
            } catch (PDOException $e) {
                $errMsg = $e->getMessage();
                if (strpos($errMsg, 'Access denied') !== false) {
                    $error = 'Erişim reddedildi — kullanıcı adı veya şifre hatalı.';
                } elseif (strpos($errMsg, 'Unknown database') !== false) {
                    $error = "Veritabanı '$dbName' bulunamadı. Önce hosting panelinizden oluşturun.";
                } elseif (strpos($errMsg, 'Connection refused') !== false || strpos($errMsg, 'No such host') !== false) {
                    $error = "Bağlantı reddedildi — host adresi hatalı: $dbHost";
                } else {
                    $error = 'Veritabanı bağlantı hatası: ' . $errMsg;
                }
            }
        }
    }

    // STEP 2: Create tables
    if ($step === 2) {
        try {
            // Read .env
            $lines = file(__DIR__ . '/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
            $env = [];
            foreach ($lines as $line) {
                $line = trim($line);
                if ($line === '' || $line[0] === '#') continue;
                if (strpos($line, '=') === false) continue;
                [$key, $value] = explode('=', $line, 2);
                $env[trim($key)] = trim($value);
            }

            $pdo = new PDO(
                "mysql:host=" . ($env['DB_HOST'] ?? 'localhost') . ";dbname=" . $env['DB_NAME'] . ";charset=utf8mb4",
                $env['DB_USER'], $env['DB_PASS'] ?? ''
            );
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

            // Run schema.sql
            $schemaFile = __DIR__ . '/database/schema.sql';
            if (!file_exists($schemaFile)) {
                $error = 'database/schema.sql dosyası bulunamadı!';
            } else {
                $sql = file_get_contents($schemaFile);

                // Split by semicolons but respect multi-line statements
                $pdo->exec($sql);

                $_SESSION['install_tables_ok'] = true;
                header('Location: install.php?step=3');
                exit;
            }
        } catch (PDOException $e) {
            $error = 'Tablo oluşturma hatası: ' . $e->getMessage();
        }
    }

    // STEP 3: Set admin password
    if ($step === 3) {
        $password = $_POST['password'] ?? '';
        $passwordConfirm = $_POST['password_confirm'] ?? '';

        if (strlen($password) < 6) {
            $error = 'Şifre en az 6 karakter olmalıdır.';
        } elseif ($password !== $passwordConfirm) {
            $error = 'Şifreler eşleşmiyor.';
        } else {
            try {
                $lines = file(__DIR__ . '/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
                $env = [];
                foreach ($lines as $line) {
                    $line = trim($line);
                    if ($line === '' || $line[0] === '#') continue;
                    if (strpos($line, '=') === false) continue;
                    [$key, $value] = explode('=', $line, 2);
                    $env[trim($key)] = trim($value);
                }

                $pdo = new PDO(
                    "mysql:host=" . ($env['DB_HOST'] ?? 'localhost') . ";dbname=" . $env['DB_NAME'] . ";charset=utf8mb4",
                    $env['DB_USER'], $env['DB_PASS'] ?? ''
                );
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

                // Hash password and save
                $hash = password_hash($password, PASSWORD_DEFAULT);
                $stmt = $pdo->prepare("UPDATE settings SET user_password = ? WHERE id = 1");
                $stmt->execute([$hash]);

                // Generate a random cron secret key
                $cronSecret = bin2hex(random_bytes(16));
                $pdo->prepare("UPDATE settings SET cron_secret_key = ? WHERE id = 1")->execute([$cronSecret]);

                // Clear session
                unset($_SESSION['install_db_ok'], $_SESSION['install_tables_ok']);

                $success = 'Kurulum tamamlandı! Giriş sayfasına yönlendiriliyorsunuz...';
                header('Refresh: 3; url=login.php');
            } catch (Exception $e) {
                $error = 'Şifre kaydetme hatası: ' . $e->getMessage();
            }
        }
    }
}

// ============================================================
// Determine which steps are completed
// ============================================================
$envExists = file_exists(__DIR__ . '/.env');
$dbConnected = $envExists || !empty($_SESSION['install_db_ok']);
$tablesCreated = !empty($_SESSION['install_tables_ok']);

// Auto-advance if steps are already done
if ($step === 1 && $envExists) {
    try {
        $lines = file(__DIR__ . '/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        $env = [];
        foreach ($lines as $line) {
            $line = trim($line);
            if ($line === '' || $line[0] === '#') continue;
            if (strpos($line, '=') === false) continue;
            [$key, $value] = explode('=', $line, 2);
            $env[trim($key)] = trim($value);
        }
        new PDO("mysql:host=" . ($env['DB_HOST'] ?? 'localhost') . ";dbname=" . $env['DB_NAME'], $env['DB_USER'], $env['DB_PASS'] ?? '');
        $step = 2;
        $dbConnected = true;
    } catch (Exception $e) {
        // .env broken, stay on step 1
    }
}
?>
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zoho-Parasut-Sync — Kurulum Sihirbazı</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: 'Inter', -apple-system, sans-serif;
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
            color: #e2e8f0;
        }
        .wizard-container {
            width: 100%;
            max-width: 560px;
        }
        .wizard-header {
            text-align: center;
            margin-bottom: 2rem;
        }
        .wizard-header h1 {
            font-size: 1.75rem;
            font-weight: 700;
            background: linear-gradient(135deg, #60a5fa, #a78bfa);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 0.5rem;
        }
        .wizard-header p {
            color: #94a3b8;
            font-size: 0.9rem;
        }

        /* Steps Progress */
        .steps {
            display: flex;
            justify-content: center;
            gap: 0;
            margin-bottom: 2rem;
        }
        .step-item {
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }
        .step-circle {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 600;
            font-size: 0.85rem;
            border: 2px solid #334155;
            color: #64748b;
            background: #1e293b;
            transition: all 0.3s;
        }
        .step-item.active .step-circle {
            border-color: #60a5fa;
            color: #60a5fa;
            background: rgba(96, 165, 250, 0.1);
        }
        .step-item.done .step-circle {
            border-color: #34d399;
            color: #fff;
            background: #34d399;
        }
        .step-line {
            width: 50px;
            height: 2px;
            background: #334155;
            margin: 0 0.25rem;
        }
        .step-item.done + .step-line,
        .step-line.done {
            background: #34d399;
        }
        .step-label {
            display: none;
        }

        /* Card */
        .wizard-card {
            background: rgba(30, 41, 59, 0.8);
            border: 1px solid rgba(71, 85, 105, 0.4);
            border-radius: 16px;
            padding: 2rem;
            backdrop-filter: blur(10px);
        }
        .wizard-card h2 {
            font-size: 1.2rem;
            font-weight: 600;
            margin-bottom: 0.5rem;
        }
        .wizard-card .subtitle {
            color: #94a3b8;
            font-size: 0.85rem;
            margin-bottom: 1.5rem;
        }

        /* Form */
        .form-group {
            margin-bottom: 1.25rem;
        }
        .form-group label {
            display: block;
            font-size: 0.8rem;
            font-weight: 500;
            color: #94a3b8;
            margin-bottom: 0.4rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }
        .form-group input {
            width: 100%;
            padding: 0.7rem 1rem;
            border: 1px solid #334155;
            border-radius: 8px;
            background: #0f172a;
            color: #e2e8f0;
            font-size: 0.95rem;
            font-family: inherit;
            transition: border-color 0.2s;
        }
        .form-group input:focus {
            outline: none;
            border-color: #60a5fa;
            box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.15);
        }
        .form-group input::placeholder {
            color: #475569;
        }
        .form-group .hint {
            font-size: 0.75rem;
            color: #64748b;
            margin-top: 0.3rem;
        }

        /* Buttons */
        .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            padding: 0.75rem 1.5rem;
            border-radius: 8px;
            font-size: 0.95rem;
            font-weight: 600;
            cursor: pointer;
            border: none;
            transition: all 0.2s;
            width: 100%;
            margin-top: 0.5rem;
        }
        .btn-primary {
            background: linear-gradient(135deg, #3b82f6, #6366f1);
            color: white;
        }
        .btn-primary:hover {
            transform: translateY(-1px);
            box-shadow: 0 4px 15px rgba(99, 102, 241, 0.4);
        }
        .btn-success {
            background: linear-gradient(135deg, #10b981, #059669);
            color: white;
        }
        .btn-success:hover {
            transform: translateY(-1px);
            box-shadow: 0 4px 15px rgba(16, 185, 129, 0.4);
        }

        /* Alerts */
        .alert {
            padding: 0.75rem 1rem;
            border-radius: 8px;
            font-size: 0.85rem;
            margin-bottom: 1rem;
        }
        .alert-error {
            background: rgba(239, 68, 68, 0.15);
            border: 1px solid rgba(239, 68, 68, 0.3);
            color: #fca5a5;
        }
        .alert-success {
            background: rgba(16, 185, 129, 0.15);
            border: 1px solid rgba(16, 185, 129, 0.3);
            color: #6ee7b7;
        }

        /* Requirements checklist */
        .requirements {
            list-style: none;
            margin-bottom: 1.5rem;
        }
        .requirements li {
            padding: 0.5rem 0;
            display: flex;
            align-items: center;
            gap: 0.75rem;
            font-size: 0.9rem;
            border-bottom: 1px solid rgba(51, 65, 85, 0.5);
        }
        .requirements li:last-child { border: none; }
        .req-ok { color: #34d399; }
        .req-fail { color: #f87171; }
    </style>
</head>
<body>
    <div class="wizard-container">
        <div class="wizard-header">
            <h1>⚡ Zoho-Parasut-Sync</h1>
            <p>Kurulum Sihirbazı</p>
        </div>

        <!-- Progress Steps -->
        <div class="steps">
            <div class="step-item <?= $step >= 1 ? ($step > 1 || $dbConnected ? 'done' : 'active') : '' ?>">
                <div class="step-circle"><?= ($step > 1 || ($step === 1 && $dbConnected)) ? '✓' : '1' ?></div>
            </div>
            <div class="step-line <?= $step > 1 ? 'done' : '' ?>"></div>
            <div class="step-item <?= $step === 2 ? 'active' : ($step > 2 ? 'done' : '') ?>">
                <div class="step-circle"><?= $step > 2 ? '✓' : '2' ?></div>
            </div>
            <div class="step-line <?= $step > 2 ? 'done' : '' ?>"></div>
            <div class="step-item <?= $step === 3 ? 'active' : ($success ? 'done' : '') ?>">
                <div class="step-circle"><?= $success ? '✓' : '3' ?></div>
            </div>
        </div>

        <div class="wizard-card">
            <?php if ($error): ?>
                <div class="alert alert-error">❌ <?= htmlspecialchars($error) ?></div>
            <?php endif; ?>
            <?php if ($success): ?>
                <div class="alert alert-success">✅ <?= htmlspecialchars($success) ?></div>
            <?php endif; ?>

            <?php if ($step === 1): ?>
                <!-- STEP 1: Database Connection -->
                <h2>📦 Veritabanı Bağlantısı</h2>
                <p class="subtitle">MySQL/MariaDB bağlantı bilgilerinizi girin. Bu bilgiler .env dosyasına kaydedilecek.</p>

                <?php
                // System requirements check
                $phpOk = version_compare(PHP_VERSION, '7.4.0', '>=');
                $pdoOk = extension_loaded('pdo_mysql');
                $curlOk = extension_loaded('curl');
                $jsonOk = extension_loaded('json');
                $writableOk = is_writable(__DIR__);
                $allOk = $phpOk && $pdoOk && $curlOk && $jsonOk && $writableOk;
                ?>

                <ul class="requirements">
                    <li>
                        <span class="<?= $phpOk ? 'req-ok' : 'req-fail' ?>"><?= $phpOk ? '✓' : '✗' ?></span>
                        PHP <?= PHP_VERSION ?> (min. 7.4 gerekli)
                    </li>
                    <li>
                        <span class="<?= $pdoOk ? 'req-ok' : 'req-fail' ?>"><?= $pdoOk ? '✓' : '✗' ?></span>
                        PDO MySQL Extension
                    </li>
                    <li>
                        <span class="<?= $curlOk ? 'req-ok' : 'req-fail' ?>"><?= $curlOk ? '✓' : '✗' ?></span>
                        cURL Extension
                    </li>
                    <li>
                        <span class="<?= $writableOk ? 'req-ok' : 'req-fail' ?>"><?= $writableOk ? '✓' : '✗' ?></span>
                        Dizin yazılabilir (<?= __DIR__ ?>)
                    </li>
                </ul>

                <?php if (!$allOk): ?>
                    <div class="alert alert-error">Yukarıdaki gereksinimlerin tümü karşılanmalıdır.</div>
                <?php else: ?>
                    <form method="POST" action="install.php?step=1">
                        <div class="form-group">
                            <label>Veritabanı Sunucusu</label>
                            <input type="text" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" placeholder="localhost">
                        </div>
                        <div class="form-group">
                            <label>Veritabanı Adı</label>
                            <input type="text" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? '') ?>" placeholder="zoho_parasut_sync" required>
                            <div class="hint">Hosting panelinizden önceden oluşturmuş olmanız gerekir.</div>
                        </div>
                        <div class="form-group">
                            <label>Kullanıcı Adı</label>
                            <input type="text" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" placeholder="root" required>
                        </div>
                        <div class="form-group">
                            <label>Şifre</label>
                            <input type="password" name="db_pass" value="" placeholder="Veritabanı şifresi">
                        </div>
                        <button type="submit" class="btn btn-primary">Bağlantıyı Test Et ve Devam Et →</button>
                    </form>
                <?php endif; ?>

            <?php elseif ($step === 2): ?>
                <!-- STEP 2: Create Tables -->
                <h2>🗄️ Veritabanı Tabloları</h2>
                <p class="subtitle">Gerekli tablolar veritabanınıza oluşturulacak (15 tablo).</p>

                <ul class="requirements">
                    <li><span class="req-ok">✓</span> Veritabanı bağlantısı başarılı</li>
                    <li><span class="<?= file_exists(__DIR__ . '/database/schema.sql') ? 'req-ok' : 'req-fail' ?>">
                        <?= file_exists(__DIR__ . '/database/schema.sql') ? '✓' : '✗' ?></span>
                        database/schema.sql dosyası mevcut
                    </li>
                </ul>

                <form method="POST" action="install.php?step=2">
                    <button type="submit" class="btn btn-primary">Tabloları Oluştur →</button>
                </form>

            <?php elseif ($step === 3): ?>
                <!-- STEP 3: Admin Password -->
                <h2>🔐 Admin Hesabı</h2>
                <p class="subtitle">Yönetim paneline giriş için bir şifre belirleyin.</p>

                <?php if (!$success): ?>
                    <form method="POST" action="install.php?step=3">
                        <div class="form-group">
                            <label>Şifre</label>
                            <input type="password" name="password" minlength="6" required placeholder="En az 6 karakter">
                        </div>
                        <div class="form-group">
                            <label>Şifre Tekrar</label>
                            <input type="password" name="password_confirm" minlength="6" required placeholder="Şifrenizi tekrar girin">
                        </div>
                        <button type="submit" class="btn btn-success">Kurulumu Tamamla ✓</button>
                    </form>
                <?php endif; ?>

                <?php if ($success): ?>
                    <p style="text-align: center; margin-top: 1rem;">
                        <a href="login.php" style="color: #60a5fa; text-decoration: none; font-weight: 600;">Giriş sayfasına git →</a>
                    </p>
                    <div style="margin-top:1.5rem; padding:1rem; border-radius:8px; background:rgba(15,23,42,0.6); font-size:0.8rem; color:#94a3b8;">
                        <strong style="color:#e2e8f0;">Sonraki Adımlar:</strong><br>
                        1. Giriş yap → <strong>Ayarlar</strong> sayfasını aç<br>
                        2. Zoho CRM API bilgilerini gir (Client ID, Secret, Refresh Token)<br>
                        3. Paraşüt API bilgilerini gir<br>
                        4. İlk senkronizasyonu başlat!
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>

        <p style="text-align: center; margin-top: 1.5rem; color: #475569; font-size: 0.75rem;">
            Zoho-Parasut-Sync v2.7 — Kurulum Sihirbazı
        </p>
    </div>
</body>
</html>
